# coding: utf-8

"""
    EVE Swagger Interface

    An OpenAPI for EVE Online

    OpenAPI spec version: 0.4.6
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from pprint import pformat
from six import iteritems
import re


class GetCharactersCharacterIdMail200Ok(object):
    """
    NOTE: This class is auto generated by the swagger code generator program.
    Do not edit the class manually.
    """
    def __init__(self, _from=None, is_read=None, labels=None, mail_id=None, recipients=None, subject=None, timestamp=None):
        """
        GetCharactersCharacterIdMail200Ok - a model defined in Swagger

        :param dict swaggerTypes: The key is attribute name
                                  and the value is attribute type.
        :param dict attributeMap: The key is attribute name
                                  and the value is json key in definition.
        """
        self.swagger_types = {
            '_from': 'int',
            'is_read': 'bool',
            'labels': 'list[int]',
            'mail_id': 'int',
            'recipients': 'list[GetCharactersCharacterIdMailRecipient]',
            'subject': 'str',
            'timestamp': 'datetime'
        }

        self.attribute_map = {
            '_from': 'from',
            'is_read': 'is_read',
            'labels': 'labels',
            'mail_id': 'mail_id',
            'recipients': 'recipients',
            'subject': 'subject',
            'timestamp': 'timestamp'
        }

        self.__from = _from
        self._is_read = is_read
        self._labels = labels
        self._mail_id = mail_id
        self._recipients = recipients
        self._subject = subject
        self._timestamp = timestamp

    @property
    def _from(self):
        """
        Gets the _from of this GetCharactersCharacterIdMail200Ok.
        From whom the mail was sent

        :return: The _from of this GetCharactersCharacterIdMail200Ok.
        :rtype: int
        """
        return self.__from

    @_from.setter
    def _from(self, _from):
        """
        Sets the _from of this GetCharactersCharacterIdMail200Ok.
        From whom the mail was sent

        :param _from: The _from of this GetCharactersCharacterIdMail200Ok.
        :type: int
        """

        self.__from = _from

    @property
    def is_read(self):
        """
        Gets the is_read of this GetCharactersCharacterIdMail200Ok.
        is_read boolean

        :return: The is_read of this GetCharactersCharacterIdMail200Ok.
        :rtype: bool
        """
        return self._is_read

    @is_read.setter
    def is_read(self, is_read):
        """
        Sets the is_read of this GetCharactersCharacterIdMail200Ok.
        is_read boolean

        :param is_read: The is_read of this GetCharactersCharacterIdMail200Ok.
        :type: bool
        """

        self._is_read = is_read

    @property
    def labels(self):
        """
        Gets the labels of this GetCharactersCharacterIdMail200Ok.
        labels array

        :return: The labels of this GetCharactersCharacterIdMail200Ok.
        :rtype: list[int]
        """
        return self._labels

    @labels.setter
    def labels(self, labels):
        """
        Sets the labels of this GetCharactersCharacterIdMail200Ok.
        labels array

        :param labels: The labels of this GetCharactersCharacterIdMail200Ok.
        :type: list[int]
        """

        self._labels = labels

    @property
    def mail_id(self):
        """
        Gets the mail_id of this GetCharactersCharacterIdMail200Ok.
        mail_id integer

        :return: The mail_id of this GetCharactersCharacterIdMail200Ok.
        :rtype: int
        """
        return self._mail_id

    @mail_id.setter
    def mail_id(self, mail_id):
        """
        Sets the mail_id of this GetCharactersCharacterIdMail200Ok.
        mail_id integer

        :param mail_id: The mail_id of this GetCharactersCharacterIdMail200Ok.
        :type: int
        """

        self._mail_id = mail_id

    @property
    def recipients(self):
        """
        Gets the recipients of this GetCharactersCharacterIdMail200Ok.
        Recipients of the mail

        :return: The recipients of this GetCharactersCharacterIdMail200Ok.
        :rtype: list[GetCharactersCharacterIdMailRecipient]
        """
        return self._recipients

    @recipients.setter
    def recipients(self, recipients):
        """
        Sets the recipients of this GetCharactersCharacterIdMail200Ok.
        Recipients of the mail

        :param recipients: The recipients of this GetCharactersCharacterIdMail200Ok.
        :type: list[GetCharactersCharacterIdMailRecipient]
        """

        self._recipients = recipients

    @property
    def subject(self):
        """
        Gets the subject of this GetCharactersCharacterIdMail200Ok.
        Mail subject

        :return: The subject of this GetCharactersCharacterIdMail200Ok.
        :rtype: str
        """
        return self._subject

    @subject.setter
    def subject(self, subject):
        """
        Sets the subject of this GetCharactersCharacterIdMail200Ok.
        Mail subject

        :param subject: The subject of this GetCharactersCharacterIdMail200Ok.
        :type: str
        """

        self._subject = subject

    @property
    def timestamp(self):
        """
        Gets the timestamp of this GetCharactersCharacterIdMail200Ok.
        When the mail was sent

        :return: The timestamp of this GetCharactersCharacterIdMail200Ok.
        :rtype: datetime
        """
        return self._timestamp

    @timestamp.setter
    def timestamp(self, timestamp):
        """
        Sets the timestamp of this GetCharactersCharacterIdMail200Ok.
        When the mail was sent

        :param timestamp: The timestamp of this GetCharactersCharacterIdMail200Ok.
        :type: datetime
        """

        self._timestamp = timestamp

    def to_dict(self):
        """
        Returns the model properties as a dict
        """
        result = {}

        for attr, _ in iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value

        return result

    def to_str(self):
        """
        Returns the string representation of the model
        """
        return pformat(self.to_dict())

    def __repr__(self):
        """
        For `print` and `pprint`
        """
        return self.to_str()

    def __eq__(self, other):
        """
        Returns true if both objects are equal
        """
        if not isinstance(other, GetCharactersCharacterIdMail200Ok):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """
        Returns true if both objects are not equal
        """
        return not self == other
