# coding: utf-8

"""
    EVE Swagger Interface

    An OpenAPI for EVE Online

    OpenAPI spec version: 0.4.6
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from pprint import pformat
from six import iteritems
import re


class GetMarketsGroupsMarketGroupIdOk(object):
    """
    NOTE: This class is auto generated by the swagger code generator program.
    Do not edit the class manually.
    """
    def __init__(self, description=None, market_group_id=None, name=None, parent_group_id=None, types=None):
        """
        GetMarketsGroupsMarketGroupIdOk - a model defined in Swagger

        :param dict swaggerTypes: The key is attribute name
                                  and the value is attribute type.
        :param dict attributeMap: The key is attribute name
                                  and the value is json key in definition.
        """
        self.swagger_types = {
            'description': 'str',
            'market_group_id': 'int',
            'name': 'str',
            'parent_group_id': 'int',
            'types': 'list[int]'
        }

        self.attribute_map = {
            'description': 'description',
            'market_group_id': 'market_group_id',
            'name': 'name',
            'parent_group_id': 'parent_group_id',
            'types': 'types'
        }

        self._description = description
        self._market_group_id = market_group_id
        self._name = name
        self._parent_group_id = parent_group_id
        self._types = types

    @property
    def description(self):
        """
        Gets the description of this GetMarketsGroupsMarketGroupIdOk.
        description string

        :return: The description of this GetMarketsGroupsMarketGroupIdOk.
        :rtype: str
        """
        return self._description

    @description.setter
    def description(self, description):
        """
        Sets the description of this GetMarketsGroupsMarketGroupIdOk.
        description string

        :param description: The description of this GetMarketsGroupsMarketGroupIdOk.
        :type: str
        """
        if description is None:
            raise ValueError("Invalid value for `description`, must not be `None`")

        self._description = description

    @property
    def market_group_id(self):
        """
        Gets the market_group_id of this GetMarketsGroupsMarketGroupIdOk.
        market_group_id integer

        :return: The market_group_id of this GetMarketsGroupsMarketGroupIdOk.
        :rtype: int
        """
        return self._market_group_id

    @market_group_id.setter
    def market_group_id(self, market_group_id):
        """
        Sets the market_group_id of this GetMarketsGroupsMarketGroupIdOk.
        market_group_id integer

        :param market_group_id: The market_group_id of this GetMarketsGroupsMarketGroupIdOk.
        :type: int
        """
        if market_group_id is None:
            raise ValueError("Invalid value for `market_group_id`, must not be `None`")

        self._market_group_id = market_group_id

    @property
    def name(self):
        """
        Gets the name of this GetMarketsGroupsMarketGroupIdOk.
        name string

        :return: The name of this GetMarketsGroupsMarketGroupIdOk.
        :rtype: str
        """
        return self._name

    @name.setter
    def name(self, name):
        """
        Sets the name of this GetMarketsGroupsMarketGroupIdOk.
        name string

        :param name: The name of this GetMarketsGroupsMarketGroupIdOk.
        :type: str
        """
        if name is None:
            raise ValueError("Invalid value for `name`, must not be `None`")

        self._name = name

    @property
    def parent_group_id(self):
        """
        Gets the parent_group_id of this GetMarketsGroupsMarketGroupIdOk.
        parent_group_id integer

        :return: The parent_group_id of this GetMarketsGroupsMarketGroupIdOk.
        :rtype: int
        """
        return self._parent_group_id

    @parent_group_id.setter
    def parent_group_id(self, parent_group_id):
        """
        Sets the parent_group_id of this GetMarketsGroupsMarketGroupIdOk.
        parent_group_id integer

        :param parent_group_id: The parent_group_id of this GetMarketsGroupsMarketGroupIdOk.
        :type: int
        """

        self._parent_group_id = parent_group_id

    @property
    def types(self):
        """
        Gets the types of this GetMarketsGroupsMarketGroupIdOk.
        types array

        :return: The types of this GetMarketsGroupsMarketGroupIdOk.
        :rtype: list[int]
        """
        return self._types

    @types.setter
    def types(self, types):
        """
        Sets the types of this GetMarketsGroupsMarketGroupIdOk.
        types array

        :param types: The types of this GetMarketsGroupsMarketGroupIdOk.
        :type: list[int]
        """
        if types is None:
            raise ValueError("Invalid value for `types`, must not be `None`")

        self._types = types

    def to_dict(self):
        """
        Returns the model properties as a dict
        """
        result = {}

        for attr, _ in iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value

        return result

    def to_str(self):
        """
        Returns the string representation of the model
        """
        return pformat(self.to_dict())

    def __repr__(self):
        """
        For `print` and `pprint`
        """
        return self.to_str()

    def __eq__(self, other):
        """
        Returns true if both objects are equal
        """
        if not isinstance(other, GetMarketsGroupsMarketGroupIdOk):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """
        Returns true if both objects are not equal
        """
        return not self == other
