# coding: utf-8

"""
    EVE Swagger Interface

    An OpenAPI for EVE Online

    OpenAPI spec version: 0.4.6
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from pprint import pformat
from six import iteritems
import re


class GetIndustryFacilities200Ok(object):
    """
    NOTE: This class is auto generated by the swagger code generator program.
    Do not edit the class manually.
    """
    def __init__(self, facility_id=None, owner_id=None, region_id=None, solar_system_id=None, tax=None, type_id=None):
        """
        GetIndustryFacilities200Ok - a model defined in Swagger

        :param dict swaggerTypes: The key is attribute name
                                  and the value is attribute type.
        :param dict attributeMap: The key is attribute name
                                  and the value is json key in definition.
        """
        self.swagger_types = {
            'facility_id': 'int',
            'owner_id': 'int',
            'region_id': 'int',
            'solar_system_id': 'int',
            'tax': 'float',
            'type_id': 'int'
        }

        self.attribute_map = {
            'facility_id': 'facility_id',
            'owner_id': 'owner_id',
            'region_id': 'region_id',
            'solar_system_id': 'solar_system_id',
            'tax': 'tax',
            'type_id': 'type_id'
        }

        self._facility_id = facility_id
        self._owner_id = owner_id
        self._region_id = region_id
        self._solar_system_id = solar_system_id
        self._tax = tax
        self._type_id = type_id

    @property
    def facility_id(self):
        """
        Gets the facility_id of this GetIndustryFacilities200Ok.
        ID of the facility

        :return: The facility_id of this GetIndustryFacilities200Ok.
        :rtype: int
        """
        return self._facility_id

    @facility_id.setter
    def facility_id(self, facility_id):
        """
        Sets the facility_id of this GetIndustryFacilities200Ok.
        ID of the facility

        :param facility_id: The facility_id of this GetIndustryFacilities200Ok.
        :type: int
        """
        if facility_id is None:
            raise ValueError("Invalid value for `facility_id`, must not be `None`")

        self._facility_id = facility_id

    @property
    def owner_id(self):
        """
        Gets the owner_id of this GetIndustryFacilities200Ok.
        Owner of the facility

        :return: The owner_id of this GetIndustryFacilities200Ok.
        :rtype: int
        """
        return self._owner_id

    @owner_id.setter
    def owner_id(self, owner_id):
        """
        Sets the owner_id of this GetIndustryFacilities200Ok.
        Owner of the facility

        :param owner_id: The owner_id of this GetIndustryFacilities200Ok.
        :type: int
        """
        if owner_id is None:
            raise ValueError("Invalid value for `owner_id`, must not be `None`")

        self._owner_id = owner_id

    @property
    def region_id(self):
        """
        Gets the region_id of this GetIndustryFacilities200Ok.
        Region ID where the facility is

        :return: The region_id of this GetIndustryFacilities200Ok.
        :rtype: int
        """
        return self._region_id

    @region_id.setter
    def region_id(self, region_id):
        """
        Sets the region_id of this GetIndustryFacilities200Ok.
        Region ID where the facility is

        :param region_id: The region_id of this GetIndustryFacilities200Ok.
        :type: int
        """
        if region_id is None:
            raise ValueError("Invalid value for `region_id`, must not be `None`")

        self._region_id = region_id

    @property
    def solar_system_id(self):
        """
        Gets the solar_system_id of this GetIndustryFacilities200Ok.
        Solar system ID where the facility is

        :return: The solar_system_id of this GetIndustryFacilities200Ok.
        :rtype: int
        """
        return self._solar_system_id

    @solar_system_id.setter
    def solar_system_id(self, solar_system_id):
        """
        Sets the solar_system_id of this GetIndustryFacilities200Ok.
        Solar system ID where the facility is

        :param solar_system_id: The solar_system_id of this GetIndustryFacilities200Ok.
        :type: int
        """
        if solar_system_id is None:
            raise ValueError("Invalid value for `solar_system_id`, must not be `None`")

        self._solar_system_id = solar_system_id

    @property
    def tax(self):
        """
        Gets the tax of this GetIndustryFacilities200Ok.
        Tax imposed by the facility

        :return: The tax of this GetIndustryFacilities200Ok.
        :rtype: float
        """
        return self._tax

    @tax.setter
    def tax(self, tax):
        """
        Sets the tax of this GetIndustryFacilities200Ok.
        Tax imposed by the facility

        :param tax: The tax of this GetIndustryFacilities200Ok.
        :type: float
        """

        self._tax = tax

    @property
    def type_id(self):
        """
        Gets the type_id of this GetIndustryFacilities200Ok.
        Type ID of the facility

        :return: The type_id of this GetIndustryFacilities200Ok.
        :rtype: int
        """
        return self._type_id

    @type_id.setter
    def type_id(self, type_id):
        """
        Sets the type_id of this GetIndustryFacilities200Ok.
        Type ID of the facility

        :param type_id: The type_id of this GetIndustryFacilities200Ok.
        :type: int
        """
        if type_id is None:
            raise ValueError("Invalid value for `type_id`, must not be `None`")

        self._type_id = type_id

    def to_dict(self):
        """
        Returns the model properties as a dict
        """
        result = {}

        for attr, _ in iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value

        return result

    def to_str(self):
        """
        Returns the string representation of the model
        """
        return pformat(self.to_dict())

    def __repr__(self):
        """
        For `print` and `pprint`
        """
        return self.to_str()

    def __eq__(self, other):
        """
        Returns true if both objects are equal
        """
        if not isinstance(other, GetIndustryFacilities200Ok):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """
        Returns true if both objects are not equal
        """
        return not self == other
