# coding: utf-8

"""
    EVE Swagger Interface

    An OpenAPI for EVE Online

    OpenAPI spec version: 0.4.6
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from pprint import pformat
from six import iteritems
import re


class GetCharactersCharacterIdWallets200Ok(object):
    """
    NOTE: This class is auto generated by the swagger code generator program.
    Do not edit the class manually.
    """
    def __init__(self, balance=None, wallet_id=None):
        """
        GetCharactersCharacterIdWallets200Ok - a model defined in Swagger

        :param dict swaggerTypes: The key is attribute name
                                  and the value is attribute type.
        :param dict attributeMap: The key is attribute name
                                  and the value is json key in definition.
        """
        self.swagger_types = {
            'balance': 'int',
            'wallet_id': 'int'
        }

        self.attribute_map = {
            'balance': 'balance',
            'wallet_id': 'wallet_id'
        }

        self._balance = balance
        self._wallet_id = wallet_id

    @property
    def balance(self):
        """
        Gets the balance of this GetCharactersCharacterIdWallets200Ok.
        Wallet's balance in ISK hundredths.

        :return: The balance of this GetCharactersCharacterIdWallets200Ok.
        :rtype: int
        """
        return self._balance

    @balance.setter
    def balance(self, balance):
        """
        Sets the balance of this GetCharactersCharacterIdWallets200Ok.
        Wallet's balance in ISK hundredths.

        :param balance: The balance of this GetCharactersCharacterIdWallets200Ok.
        :type: int
        """

        self._balance = balance

    @property
    def wallet_id(self):
        """
        Gets the wallet_id of this GetCharactersCharacterIdWallets200Ok.
        wallet_id integer

        :return: The wallet_id of this GetCharactersCharacterIdWallets200Ok.
        :rtype: int
        """
        return self._wallet_id

    @wallet_id.setter
    def wallet_id(self, wallet_id):
        """
        Sets the wallet_id of this GetCharactersCharacterIdWallets200Ok.
        wallet_id integer

        :param wallet_id: The wallet_id of this GetCharactersCharacterIdWallets200Ok.
        :type: int
        """

        self._wallet_id = wallet_id

    def to_dict(self):
        """
        Returns the model properties as a dict
        """
        result = {}

        for attr, _ in iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value

        return result

    def to_str(self):
        """
        Returns the string representation of the model
        """
        return pformat(self.to_dict())

    def __repr__(self):
        """
        For `print` and `pprint`
        """
        return self.to_str()

    def __eq__(self, other):
        """
        Returns true if both objects are equal
        """
        if not isinstance(other, GetCharactersCharacterIdWallets200Ok):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """
        Returns true if both objects are not equal
        """
        return not self == other
