# coding: utf-8

"""
    EVE Swagger Interface

    An OpenAPI for EVE Online

    OpenAPI spec version: 0.4.6
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from pprint import pformat
from six import iteritems
import re


class PostFleetsFleetIdWingsWingIdSquadsCreated(object):
    """
    NOTE: This class is auto generated by the swagger code generator program.
    Do not edit the class manually.
    """
    def __init__(self, squad_id=None):
        """
        PostFleetsFleetIdWingsWingIdSquadsCreated - a model defined in Swagger

        :param dict swaggerTypes: The key is attribute name
                                  and the value is attribute type.
        :param dict attributeMap: The key is attribute name
                                  and the value is json key in definition.
        """
        self.swagger_types = {
            'squad_id': 'int'
        }

        self.attribute_map = {
            'squad_id': 'squad_id'
        }

        self._squad_id = squad_id

    @property
    def squad_id(self):
        """
        Gets the squad_id of this PostFleetsFleetIdWingsWingIdSquadsCreated.
        The squad_id of the newly created squad

        :return: The squad_id of this PostFleetsFleetIdWingsWingIdSquadsCreated.
        :rtype: int
        """
        return self._squad_id

    @squad_id.setter
    def squad_id(self, squad_id):
        """
        Sets the squad_id of this PostFleetsFleetIdWingsWingIdSquadsCreated.
        The squad_id of the newly created squad

        :param squad_id: The squad_id of this PostFleetsFleetIdWingsWingIdSquadsCreated.
        :type: int
        """
        if squad_id is None:
            raise ValueError("Invalid value for `squad_id`, must not be `None`")

        self._squad_id = squad_id

    def to_dict(self):
        """
        Returns the model properties as a dict
        """
        result = {}

        for attr, _ in iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value

        return result

    def to_str(self):
        """
        Returns the string representation of the model
        """
        return pformat(self.to_dict())

    def __repr__(self):
        """
        For `print` and `pprint`
        """
        return self.to_str()

    def __eq__(self, other):
        """
        Returns true if both objects are equal
        """
        if not isinstance(other, PostFleetsFleetIdWingsWingIdSquadsCreated):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """
        Returns true if both objects are not equal
        """
        return not self == other
